col.sex <- c(Female = "deeppink3", Male = "deepskyblue3")
col.line <- c('3B' = "darkolivegreen2", '6A'="darkolivegreen3", '10B'="darkorange2", '12B'="darkorange3")
col.cross <- c('10b x 3b' = "orchid3", '12b x 3b' = "orchid4")
pch.cross <- c('10b x 3b' = 19, '12b x 3b' = 15)
col.medium <- c(A="gold3", C="lightsalmon2", G="pink3")
